---
# yamllint disable rule:truthy
name: Lint

env:
  SHELLCHECK_OPTS: -e SC1008,SC2016,SC2038 -s bash

on:
  pull_request:
  push:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    name: YAMLLint
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run YAMLLint
        uses: frenck/action-yamllint@v1.3

  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run linter
        uses: ludeeus/action-shellcheck@1.1.0
